### ISSUE TITLE
add software and version for the creation of schematics, pcbs, and cad designs.

### ISSUE THREAD

**Issue by mxochicale** [microsoft/Microsecond-Arduino-Latency-Clock#1]
HI @margonzalezfranco

Very nice work! To make a more reproducible work, perhaps you can add the software and version used to create your schematics, pcbs, and cad designs.

Miguel

**Comment by robgruen** [comment]
I just added the project files for the schematic, pcb, and cad designs.  Created with Eagle v9.5.2.

**Comment by anonymous-mgf** [comment]
Hi We have added
the project files for the schematic, pcb, and cad designs. Created with Eagle v9.5.2.


Sent from my phone

On Mar 26, 2020, at 6:20 AM, Miguel Xochicale <notifications@github.com> wrote:

﻿

HI @margonzalezfranco<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmargonzalezfranco&data=02%7C01%7Cmargon%40microsoft.com%7C78e6e67c25534e314b4c08d7d1886d06%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208256189188338&sdata=WlBrq7cukZZJ%2F0NIVeNFtQhoiCZCh9eBQiD7TDwM2nM%3D&reserved=0>

Very nice work! To make a more reproducible work, perhaps you can add the software and version used to create your schematics, pcbs, and cad designs.

Miguel
